resources:
  - name: pack_conf_repo
    type: gitRepo
    integration: drship_github
    versionTemplate:
      sourceName: devops-recipes/gcp_image_with_packer
      branch: master

  - name: img_gcp_cli
    type: cliConfig
    integration: drship_gcp
    versionTemplate:
      region: "us-west1-a"

jobs:
  - name: prep_u16_gce_image
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: pack_conf_repo
      - IN: img_gcp_cli
        switch: off
      - TASK:
          name: prep_u16_gce_image
          runtime:
            options:
              env:
                - SOURCE_IMAGE_FAMILY: "ubuntu-1604-lts"
                - MACHINE_TYPE: "n1-standard-1"
                - REGION: "europe-west1"
                - ZONE: "europe-west1-b"
                - PROJECT_ID: "devops-recipes"
          script:
            - pushd $(shipctl get_resource_state "pack_conf_repo")/u16image
#            - echo $(shipctl get_integration_resource_field img_gcp_cli JSON_key) > gcp_key.json
#            - export SERVICE_ACCOUNT_JSON="gcp_key.json"
            - packer validate baseAMI.json
            - packer build -machine-readable \
                -var aws_access_key=$AWS_ACCESS_KEY_ID \
                -var aws_secret_key=$AWS_SECRET_ACCESS_KEY \
                -var REGION=$REGION \
                -var VPC_ID=$VPC_ID \
                -var SUBNET_ID=$SUBNET_ID \
                -var SECURITY_GROUP_ID=$SECURITY_GROUP_ID \
                -var SOURCE_AMI=$SOURCE_AMI \
                -var IMAGE_NAMES_SPACED="${IMAGE_NAMES_SPACED}" \
                -var RES_IMG_VER_NAME=$SHIPPABLE_RELEASE_VERSION \
                -var RES_IMG_VER_NAME_DASH=$SHIPPABLE_RELEASE_VERSION \
                -var SHIPPABLE_RELEASE_VERSION=$SHIPPABLE_RELEASE_VERSION \
                baseAMI.json 2>&1 | tee output.txt
            - cat output.txt
#            - ./basePack.sh u16baseami_prep ami_bits_access_cli
            - popd
#    on_failure:
#      - script: cat $(shipctl get_resource_state prepami_repo)/u16Base/output.txt
    flags:
      - gcp_packer
